credentials:
  usernames:
    usuario1:
      email: usuario1@example.com
      name: Usuario Um
      password: $2b$12$fG/FzWioMHiOVPrJKfqbQe0qrze0gZqkd.mb5q0tcnXleWKeLLGme
    usuario2:
      email: usuario2@example.com
      name: Usuario Dois
      password: $2b$12$kXB.GFlpequ0nYK03ui5L.cXEZyh4zUau/aYhjBzumKvP14pWgy8e
  
cookie:
  expiry_days: 0.013889
  key: SUA_CHAVE_DE_COOKIE_SECRETA_AQUI
  name: servmar_cookie
