credentials:
  usernames:
    user1:
      email: user1@example.com
      password: "senha123"
    user2:
      email: user2@example.com
      password: "senha456"

cookie:
  #expiry_days: 0.8 #30 minutos
  expiry_days: 0.013889 #20 minutos  
  #expiry_days: 0.0104166 #15 minutos
  #expiry_days: 0.0013888 #2 minutos
  name: cookie_name
  key: some_random_key
